language: python #language that we are going to use in the project
python: #version  of the language
  - "3.6"

services: #service include in the project
  -docker

before_script: pip install docker-compose 

script: #script to execute test(test and exclude files(flake8))
  - docker-compose run app sh -c "python manage.py test && flake8"
