# Generated by Django 2.1.15 on 2020-09-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='STATUS',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
