# Generated by Django 2.1.15 on 2020-09-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='CODE',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='estate',
            name='PUBLIC_DEED',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
